apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-local
  labels:
    type: local
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/disk/vol1"


